apiVersion: v1
kind: Secret
metadata:
  name: {{ include "one-press-chart.fullname" . }}
  labels:
{{ include "one-press-chart.labels" . | indent 4 }}
type: Opaque
data:
{{- range $c := .Values.deployment.containers }}
{{- range $key, $val := (($c.env).secret) }}
{{ $key | indent 2 }}: {{ $val | toString | b64enc }}
{{- end }}
{{- end}}
{{ (tpl (.Files.Glob .Values.secret.targetPath).AsSecrets . ) | indent 2 }}